### ISSUE TITLE
[playground] Parallelism checklist for fully demonstrating framework capability

### ISSUE THREAD

**Issue by emansipater** [counterfactual/monorepo#1062]
prerequisites: apps can use existing payment meta-channels instead of only transiting the hub directly

- [ ] Improve parallelism support in the node re: dynamically moving apps across nonce changes, state and channel management handling under close/open/fail etc.
- [ ] Harden local state management against parallel usage
- [ ] Once [meta-channel applications are based on payment channels](https://github.com/counterfactual/monorepo/issues/920) create some type of "asset bandwidth" management strategy to decide how big of payment metachannels to start with, when to expand or decrease the size of the payment metachannel to support additional apps or recover unused capital bandwidth, etc. (trades off fees and capital costs vs privacy)
- [ ] Create some reasonable UX for the above
- [ ] Ensure bots support parallelism, and adapt their "asset bandwidth" management to limit number of open apps per user and in total.
- [ ] Allow multiple versions of an app, and multiple apps, to be opened in separate tabs.

(more to be added)
