### ISSUE TITLE
[contracts] Upgrade StateChannelTransaction to accept an Interpreter argument

### ISSUE THREAD

**Issue by snario** [counterfactual/monorepo#1258]
# todo
- [x] change "resolution" to be of type `bytes` instead of `Transfer.Transaction`
- [x] add an interpreter field to `executeAppConditionalTransaction`
- [x] write interpreters for existing apps
- [ ] virtual channels

**Comment by snario** [comment]
As a note, it is the case that _some_ kinds of apps might have a logical operator seperating out how a resolution might resolve. Example: a swap option.

Resolution function of a swap option is a choice between resolving 10 ETH or 10 DAI but not both.
