### ISSUE TITLE
[testing] Implement an end-to-end test suite for Counterfactual

### ISSUE THREAD

**Issue by joelalejandro** [counterfactual/monorepo#1907]
We'll add a new package called `greenboard`. Its goal is to test a series of interaction flows simulating user input for the scenarios described in #1852.

### Task list

Work is being done in the `joel/e2e` branch (see #1906).

- [ ] Create package `greenboard`
- [ ] Install and configure `cypress` for CI runs
- [ ] Prepare a script that allows to pack an updated version of the Metamask Extension with the CF vendors to install it in Chrome
- [ ] Prepare a script that bootstraps a Metamask wallet
- [ ] Write tests for the scenarios

**Comment by joelalejandro** [comment]
We had to scrap the idea of testing with Cypress because they're not ready for Chrome Extensions yet (see cypress-io/cypress#1965). So we're moving forward with Puppeteer instead.

**Comment by joelalejandro** [comment]
Once again, scrapping an idea :man_facepalming: Puppeteer offers no API to interact with the browser toolbar, so we wouldn't be able to sign messages or deposits. Moving on to Selenium.
