### ISSUE TITLE
[wallet-ui] Show a MetaMask notification when `chan_proposeInstallVirtual` is received

### ISSUE THREAD

**Issue by joelalejandro** [counterfactual/monorepo#2144]
When a user A runs a dapp and wants to interact with user B, a `chan_proposeInstallVirtual` is used to ask the counterparty if they want to use the dapp together.

The Wallet UI must trigger a notification for user B, ideally using MetaMask's notification system.

## Task breakdown

- [ ] Add listener for `chan_proposeInstallVirtual`
- [ ] Add relay for `chan_installVirtual`
- [ ] Add relay for `chan_rejectInstall`
- [ ] Implement modal screen
- [ ] Show modal when receiving a `chan_proposeInstallVirtual` message
- [ ] Implement `chan_installVirtual` method call when clicking "Accept"
- [ ] Implement `chan_rejectInstall` method call when clicking "Reject"
