### ISSUE TITLE
[node] Symmetrical FINISHED events for all parties after protocol execution completes

### ISSUE THREAD

**Issue by rhlsthrm** [counterfactual/monorepo#2435]
Add support for `FINISHED` events to all protocols which fire when the protocol completes. These should also be passed in a message to other channel counterparties so that everyone knows when all stores have unlocked at the same time.

- [x] `SETUP_FINISHED` @ArjunBhuptani @cf19drofxots #2437 
- [ ] `DEPOSIT_FINISHED`
- [x] `INSTALL_FINISHED` - PR https://github.com/counterfactual/monorepo/pull/2438 (@LayneHaber started it, @cf19drofxots getting it over the line)
- [x] `UNINSTALL_FINISHED` @ArjunBhuptani #2440
- [ ] `INSTALL_VIRTUAL_FINISHED`
- [ ] `UNINSTALL_VIRTUAL_FINISHED`
- [x] `WITHDRAW_FINISHED` @cf19drofxots #2441

~P.s. Listening for the INSTALL event does not yield the event from the initiator.~ resolved via #2439

**Comment by rhlsthrm** [comment]
So initiatior actually does emit the event, but it emits it with the RPC method name, not the event name:

https://github.com/counterfactual/monorepo/blob/master/packages/node/src/rpc-router.ts#L48

Updated the title to reflect.

**Comment by ArjunBhuptani** [comment]
`SETUP_FINISHED` PR here: https://github.com/counterfactual/monorepo/compare/setup-finished-event?expand=1

**Comment by rhlsthrm** [comment]
This issue got changed a lot from the original. The original issue that I reported is this:

> So initiatior actually does emit the event, but it emits it with the RPC method name, not the event name:
>
> https://github.com/counterfactual/monorepo/blob/master/packages/node/src/rpc-router.ts#L48
>
> Updated the title to reflect.

Currently this issue as described isn't relevant, but what I mentioned here is still an issue/
