### ISSUE TITLE
[machine] The Grand To-Do List

### ISSUE THREAD

**Issue by joelalejandro** [counterfactual/monorepo#257]
The following is a list of TODOs found in the codebase of `@counterfactual/machine/` by the end of October 2018.

All of the related issues are closed by default to make room for more current issues, but these should be addressed as well. If you see that any of the following issues should be discussed, please reopen it and comment. If an issue is already resolved, leave it closed and tick it on the list.

- [x] #83: NetworkContext shouldn't link contract byte-code relying on dynamic references and object inspection
- [ ] #84: TestResponseSink.messageListener should support multiple callbacks
- [x] #85: ActionName shouldn't mix operations and client actions
- [x] #93: TestResponseSink.validateSignatures() shouldn't throw an error if signatures do not match 
- [x] #94: TestIoProvider.ioSendMessage() could receive `msg.value` as null
- [x] #95: Code in TestIoProvider.listenOnce() has @ts-ignore annotations 
- [x] #97: TestIoProvider.peer shouldn't be initialized as a null TestResponseSink
- [x] #98: TestIoProvider shouldn't import functions from the source code
- [ ] #99: Attempts to make a commitment with a missing counterparty signature shouldn't throw an unhandled error
- [ ] #100: Commitments interface shouldn't use a Map for storing commitments
- [ ] #101: TestCommitmentStore.addCommitment() shouldn't allow any other action other than UPDATE if there are any actions in `commitments` collection 
- [ ] #102: Integration tests in ResumeProtocolSpec shouldn't print out deliberately-thrown errors as "real" errors
- [x] #103: Integration tests for CfOperations shouldn't depend on Ganache
- [ ] #107: TestResponseSink.responseListener should support multiple callbacks
- [ ] #108: TestResponseSink requires clarification on why is necessary to bind ACK methods between the IO protocol and VM
- [x] #109: Document that state proposals require valid Ethereum addresses, otherwise the proposers will fail
- [x] #110: Document that signingKey.address *must* be a hex, otherwise InstallProposer will fail
- [x] #111: Several integration test functions lack nonce + uniqueId validation
- [x] #112: Initcode encoding shouldn't have a hardcoded timeout 
- [ ] #113: CfOperations tests should use a ProxyFactory instead of manually linking bytcode
- [x] #114: Should remove `tslint:disable-next-line` from CfOperations tests for number-named references 
- [ ] #116: KeyGenerator.generate() must assign ephemeral keys 
- [x] #117: CfFreeBalance.terms() should not use a hard-coded limit
- [x] #118: CfFreeBalance requires implementation changes on the contracts layer
- [x] #119: CfAppInterface.hash() shouldn't console.error() if address is 0x0 
- [x] #120: EthCfOpGenerator.update() should return a CfOpSetState with app-specific ephemeral keys
- [x] #121: EthCfOpGenerator.update() shouldn't fail completely if no appID is provided
- [x] #122: Remove timeout from CfMultisendOp.dependencyNonceInput()
- [x] #124: Signature class constructor arguments need better typing
- [x] #125: ResponseSink interface has no known purpose
- [x] #126: AppChannelInfo interface shouldn't be aware of any StateChannelInfo instance
- [x] #127: StateChannelInfo interface should't be aware of owners()
- [x] #128: ClientResponse type must be further specified (no "any" declarations)
- [ ] #129: Signing keys creation shouldn't take care of sorting such keys
- [ ] #130: SignatureValidator needs implementation 
- [ ] #132: Execution of Instruction.ALL should do middleware cascading instead of plain iteration
- [x] #133: Return a better error mesage if no middleware is found (instead of `cannot read property '0' of undefined`)
- [x] #134: Resolver code shouldn't be part of the contractInterface() method
- [x] #135: Members in `cfApp` should be typed (`any` should be removed)
- [x] #136: VM reference breaks encapsulation in ActionExecution.createContext()
- [ ] #141: TestResponseSink.sendResponse() doesn't handle not-found requests
- [x] #143: NetworkContext shouldn't link contract byte-code relying on dynamic references and object inspection
- [x] #144: ActionName shouldn't mix operations and client actions

**Comment by joelalejandro** [comment]
@snario @IIIIllllIIIIllllIIIIllllIIIIllllIIIIll This list is probably outdated by now. Care to take a look at it and see if it still makes sense to have it around?

**Comment by snario** [comment]
@joelalejandro I checked off the ones that are either not relevant or done. The rest are useful reminders.
