### ISSUE TITLE
[security] Security checklist of intentionally unsafe features to be changed before production readiness

### ISSUE THREAD

**Issue by emansipater** [counterfactual/monorepo#924]
Still need to:
- [ ] Validate app identities against an ENS registry entry to prevent app spoofing
- [ ] Validate incoming proposed Installs from both apps and counterparties against some sort of "supported apps" policy which includes user authorization (either explicitly prompted or implicit if persisted from a previous setting) instead of just acking them all
- [ ] Validate initial app states against an explicit list of per-app safety assertions which may include user authorization if needed (such as when resuming a game from a previous session, for example) instead of just blindly accepting the proposal an app generates
- [ ] Have the machine compute the balances resulting from an uninstall, don't just have the app or node assert them when requesting the uninstall
- [ ] Define a hub/intermediate node's policy for which metachannels it will allow opening across it instead of just acking them all (needs to eventually include fee policy which covers capital costs at minimum and perhaps a more complex model of overall balance topology to minimise rebalancing needs)

(list still incomplete, please add more items here)

**Comment by snario** [comment]
I think that, for each of these, we should create a new GitHub issue with the Security label.
